# Generated by Django 4.1.4 on 2022-12-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('quote_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('premium', models.DecimalField(decimal_places=2, default=100.0, max_digits=6)),
                ('cover', models.DecimalField(decimal_places=2, default=100000.0, max_digits=9)),
                ('state', models.CharField(default='New', max_length=50)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemocranceApp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Policy_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ph_state', models.CharField(max_length=50)),
                ('ph_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemocranceApp.policy')),
            ],
        ),
    ]
